version: '3.8'

services:
  postgres:
    image: postgres:15.4
    container_name: digio-db
    environment:
      POSTGRES_DB: digio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: digio123
    ports:
      - "5432:5432"
    networks:
      - digio-network

  app:
    build: .
    container_name: digio-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/digio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: digio123
    networks:
      - digio-network

networks:
  digio-network:
